app:
  schedule:
    enabled: false
    optimization: true
    period: 60000
    priceIncreasePercentage: 1.101
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
spring:
  thymeleaf:
    check-template-location: false
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.xml
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  application:
    name: zero
  datasource:
    url: jdbc:h2:mem:testdb;INIT=RUNSCRIPT FROM 'src/main/resources/h2init.sql';MODE=PostgreSQL;
    driver-class-name: org.h2.Driver
  jpa:
    show_sql: true
    properties:
      hibernate:
        show_sql: false
        generate_statistics: true
        jdbc:
          time_zone: Europe/Samara
    hibernate:
      ddl-auto: create
      hbm2ddl:
        auto: create
server:
  port: 8080