app:
  schedule:
    enabled: false
    optimization: false
    period: 60000
    priceIncreasePercentage: 1.101
spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  application:
    name: zero
  datasource:
    url: ${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show_sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Samara
    hibernate:
      show_sql: true
      ddl-auto: validate
server:
  port: 8080